---
tor_hidden_services_parent_dir: /var/lib/tor/services
tor_user: debian-tor
enable_ssh_over_tor: true

# Enabling support for trusty by default. Can be overridden to evaluate
# xenial support.
tor_apt_target_distro: "{{ ansible_distribution_release }}"
