---
# Permit direct access via SSH
ssh_net_in_override: 0.0.0.0/0

# In libvirt, we want to connect over eth0, not eth1 which is used for
# inter-VM communication for OSSEC.
ssh_ip: "{{ ansible_default_ipv4.address }}"

# Override "xenial" target with trusty, since we don't have a xenial
# channel in the apt repo yet.
apt_repo_target_distro: trusty
tor_apt_target_distro: trusty
